### ISSUE TITLE
Will Unicord v2 support W10M?

### ISSUE THREAD

**Issue by burd1** [WamWooWam/Unicord#118]
Will Unicord v2 support w10m at all later on or is it done?

**Comment by WamWooWam** [comment]
So as I said in the Discord already, here's the deal. **Yes**, but there's a lot of blockers right now:

1. Building the native library for Voice to support ARM32 is near impossible now due to the dependency on the native libwebrtc library.
2. Many dependant libraries no longer support versions of Windows 10 this old (WinUI 2.8+, CommunityToolkit 7.0+, etc.)
3. Unicord is in rough shape, it's very buggy and it's missing a lot of very basic functionality (threads, DM calls, slash commands, decent pomelo support, maybe even video?)

Right now, I wanna make sure I have implemented the basic ass functionality Unicord has been missing for 4+ years now, like the aforementioned threads, and I want to make sure it's built on a base that I can work with going forward, fixing all the things I've done Wrong historically. Only once that's done can I start working backwards and figuring out support for older versions of Windows.

I'm very aware that the vast majority of the Unicord userbase is on RS2, and I don't want anyone to think I've forgotten this,. It's just gonna take some time.

**Comment by WamWooWam** [comment]
Very early RS2 and Windows Phone support is now available in https://github.com/UnicordDev/Unicord/releases/tag/v2.0.0-alpha.6 👍
