### ISSUE TITLE
Add MIT License in all commits

### ISSUE THREAD

**Issue by Redblueflame** [WamWooWam/Unicord#18]
To avoid any licensing problem, a contributor have to add the LICENSE to every commit in the repository, without that, all commits before are not licensed, thus the code are owned by WamWooWam

**Comment by sijanec** [comment]
I think as soon as the license is added, because of Git's blockchain nature, if so is mentioned in the LICENSE file, all previous commits are licensed. There may of course be problems with other contributors that contributed before licensing, as they may not agree with their code being licensed as MIT.

It is impossible to modify previous commits in Git once they are pushed or once other commits are based upon them.

**Comment by WamWooWam** [comment]
99% of commits before this point are mine, and everyone else knew about this change beforehand so
